#!/usr/bin/env bash

if [ ! -f ".node-version" ]; then
  echo "Error: .node-version file does not exist." >&2
  exit 1
fi
if [ -z ".node_version" ]; then
  echo "Error: .node-version file is empty." >&2
  exit 1
fi
./script/ensure-nvm
export NVM_DIR="$HOME/.nvm"

# shellcheck disable=SC1091
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
node_version=$(cat .node-version)
nvm install "$node_version"
nvm use "$node_version"
